### ISSUE TITLE
Latest commits beak addon

### ISSUE THREAD

**Issue by tinzarian** [aqw/xbmc-gamepass#390]
Maybe I'm missing something, but after the latest commits the addon is broken. Playing completed games, NFL Network live or shows all result in error  (I haven't tested a live game).
After going back to the repository release everything works again. 

Log is at: http://ix.io/1kSm

**Comment by kaileu** [comment]
@tinzarian
There is no addon related stuff in the log file.
Please make sure you enabled debug log and reproduce the error and post a log again.

**Comment by aqw** [comment]
If there's breakage, it's probably the fault of my recent changes. @tinzarian Please upload a debug log and we'll look at it.

**Comment by aqw** [comment]
@tinzarian @kaileu Actually, I wrote to soon. It is a debug log. Foudn the section:
```
20:07:34.697 T:140553341630208   DEBUG: [plugin.video.nfl.gamepass-2018.08.15-dev]: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 489, in onClick
                                                self.play_url(stream_url)
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 257, in play_url
                                                playitem.setProperty('inputstream.adaptive.stream_headers', url.split('|')[1])
                                            IndexError: list index out of range
```

I don't have the time to work on this tonight, but I might be able to get into it tomorrow, unless someone beats me to it.

---Alex

**Comment by aqw** [comment]
@tinzarian I made some fixes; could you please retest?

@kaileu I'm seeing a weird problem. Games only play for me when I pass a full master m3u8 playlist (highlights work in both modes; didn't test condensed). Can you replicate this on your end? The code only passes a master m3u8 when we have inputstream enabled (which I don't), and this might be related to the problems @tinzarian ran into.

As FYI, I extended get_streams() in pigskin to return all formats, and adjusted our code to prefer chromecast streams but fallback to HLS. So we're back to the better streams. :-)

---Alex

**Comment by tinzarian** [comment]
@aqw @kaileu Still the same problem, unfortunately.
New log: http://ix.io/1kXb

**Comment by aqw** [comment]
@tinzarian Ahh, I think I found it. I'm not certain these headers are needed anymore, but I don't have the time right now to audit it.

Try with the latest code; it should fix the bug you're seeing.

---Alex

**Comment by tinzarian** [comment]
Yep, that did it, it's all working again.
